config/routes.rb
Nikrik::Application.routes.draw do

 
  resources :reminders


  devise_for :users,:path => '', path_names:{sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end


  get "welcome/index"
  get "home/admin"
  post "home/callus" => "home#callus"
  get "home/complaint" => "home#new_complaint"
  post "home/complaint" => "home#complaint"
  get "home/contactus" => "home#new_contactus"
  get "home/aboutus" => "home#aboutus"
  get "home/disclaimer" => "home#disclaimer"
  get "home/privatepolicy" => "home#privatepolicy"
  post "home/contactus" => "home#contactus"
  get "home/faq" => "home#faq"

  get "motor/idv_charts/distinctMakers" => "motor/idv_charts#distinctMakers"
  get "motor/idv_charts/modelsForAManufacturer" => "motor/idv_charts#modelsForAManufacturer"
  get "motor/idv_charts/:id/motorValue" => "motor/idv_charts#motorValue"
  get "motor/idv_charts/models" => "motor/idv_charts#models"
  get  "motor/searches/currentUser" => "motor/searches#currentUser"
  post "motor/searches/quote" => "motor/searches#quote"
  post "motor/searches/buy" => "motor/searches#buy"
  post "motor/searches/quoteEmail" => "motor/searches#quoteEmail"  
  
  post "health/searches/quote" => "health/searches#quote"
  post "health/searches/buy" => "health/searches#buy"
  post "health/searches/quoteEmail" => "health/searches#quoteEmail"  

  post "travel/searches/quote" => "travel/searches#quote"
  post "travel/searches/buy" => "travel/searches#buy"
  post "travel/searches/quoteEmail" => "travel/searches#quoteEmail"

  post "loyalty/referral" => "loyalty#create_referral"
  get  "loyalty/user_referrals" => "loyalty#user_referrals"
  get  "loyalty/find_referrals" => "loyalty#find_referrals"
  get  "loyalty/referral/:id" => "loyalty#referral"
  put "loyalty/update_referral/:id" => "loyalty#update_referral"

  get "loyalty/points" => "loyalty#points"
  get "loyalty/rewards" => "loyalty#rewards"
  get "loyalty/purchase/:id" => "loyalty#purchase"
  post "loyalty/confirm/" => "loyalty#confirm"
  get "loyalty/details/:id/:ref_type/:ref_id" => "loyalty#details"

  #post  "loyalty/referrals" => "loyalty#create_referral"
  #get   "loyalty/:userId/referrals" => "loyalty#user_referrals"  #user
  #get   "loyalty/referrals?status=:status" => "loyalty#find_referrals"
  #get   "loyalty/referrals/:id" => "loyalty#referral"
  #put   "loyalty/referrals/:id" => "loyalty#update_referral"

  #get "loyalty/:userId/points" => "loyalty#points" #user
  #get "loyalty/activeRewards" => "loyalty#rewards" #user

  get "policies/display/:id"  =>    "policies#display"
  get "policies/policies"  =>    "policies#policies"
  get "policies/download/:id"  => "policies#download"

  get "orders/user_orders"  => "orders#user_orders"

  namespace :motor do
    resources :rtos
    resources :discounts
    resources :searches
    resources :quotes
    resources :idv_charts
  end
 
 namespace :travel do
   resources :charts
 end

 namespace :health do
   resources :charts
 end

  resources :policies
  resources :rewards 
  resources :admin_users
  resources :policy_attributes
  resources :orders
  resources :static_htmls
 
  match "/delayed_job" => DelayedJobWeb, :anchor => false
 
  root :to => "welcome#index"

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  self.table_name = "rewards"
  attr_accessible :details, :end_date, :image_name, :name, :points, :start_date, :status

def self.find_active_rewards()
    where("(start_date is null or start_date <= ?) AND (end_date is null or end_date >= ?)", Time.now, Time.now)
end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end
end

app/views/rewards/_form.html.erb
<%= simple_form_for(@reward) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :details, :as => :text , :input_html => { :cols => 20, :rows => 5 } %>
    <%= f.input :points %>
    <%= f.input :image_name %>
    <%= f.input :status, :prompt => "Select Status", :collection => [ "ACTIVE", "INACTIVE"] %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rewards/_rewards_details_modal.html.erb
<!-- Modal -->
<div id="rewardDeatilsOrErrorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div id="rewardDetailsModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 class="first"></h3>
    </div>
    <div class="modal-body">
        <div id="rewards_details_body">
        	<div id="notificationDiv">
  		</div>
        	<div class="media">
    			<a class="pull-left" href="#">
      			<img class="media-object second" src="/assets/rewards/logo_1.png">
    			</a>		
  	  		<div class="media-body">
  	  			<p class="third"></p>
  	  			<hr>
  	  			<p><strong>Description:</strong><p>
  	  			<p class="fourth"></p>
  	  			<hr>
            <div class="alert alert-success notification">
            </div>
  	    		<p><button class='btn btn-danger fifth' type='button'></button></p>
  	      </div>
  	    </div>
  	   </div>
       <input type="hidden" class="status"/>
    </div>
    <div class="modal-footer">
      <button class="btn is_btn-custom" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
  <div id="errorModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Oh snap! You got an error!</h3>
    </div>
    <div class="modal-body alert alert-error first">
    </div>
    <div class="modal-footer">
        <button class="btn is_btn-custom" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
  <div id="successModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Success!</h3>
    </div>
    <div class="modal-body alert alert-success first">
    </div>
    <div class="modal-footer">
        <button class="btn is_btn-custom" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h2>Listing Rewards</h2>

<table class="table table-bordered table-striped" >
  <tr>
    <th>Name</th>
    <th>Details</th>
    <th>Points</th>
    <th>Image name</th>
    <th>Status</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.name %></td>
    <td><%= reward.details %></td>
    <td><%= reward.points %></td>
    <td><%= reward.image_name %></td>
    <td><%= reward.status %></td>
    <td><%= reward.start_date %></td>
    <td><%= reward.end_date %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reward.name %>
</p>

<p>
  <b>Details:</b>
  <%= @reward.details %>
</p>

<p>
  <b>Points:</b>
  <%= @reward.points %>
</p>

<p>
  <b>Image name:</b>
  <%= @reward.image_name %>
</p>

<p>
  <b>Status:</b>
  <%= @reward.status %>
</p>

<p>
  <b>Start date:</b>
  <%= @reward.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @reward.end_date %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>