config/routes.rb
Nikrik::Application.routes.draw do

 
  resources :reminders


  devise_for :users,:path => '', path_names:{sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end


  get "welcome/index"
  get "home/admin"
  post "home/callus" => "home#callus"
  get "home/complaint" => "home#new_complaint"
  post "home/complaint" => "home#complaint"
  get "home/contactus" => "home#new_contactus"
  get "home/aboutus" => "home#aboutus"
  get "home/disclaimer" => "home#disclaimer"
  get "home/privatepolicy" => "home#privatepolicy"
  post "home/contactus" => "home#contactus"
  get "home/faq" => "home#faq"

  get "motor/idv_charts/distinctMakers" => "motor/idv_charts#distinctMakers"
  get "motor/idv_charts/modelsForAManufacturer" => "motor/idv_charts#modelsForAManufacturer"
  get "motor/idv_charts/:id/motorValue" => "motor/idv_charts#motorValue"
  get "motor/idv_charts/models" => "motor/idv_charts#models"
  get  "motor/searches/currentUser" => "motor/searches#currentUser"
  post "motor/searches/quote" => "motor/searches#quote"
  post "motor/searches/buy" => "motor/searches#buy"
  post "motor/searches/quoteEmail" => "motor/searches#quoteEmail"  
  
  post "health/searches/quote" => "health/searches#quote"
  post "health/searches/buy" => "health/searches#buy"
  post "health/searches/quoteEmail" => "health/searches#quoteEmail"  

  post "travel/searches/quote" => "travel/searches#quote"
  post "travel/searches/buy" => "travel/searches#buy"
  post "travel/searches/quoteEmail" => "travel/searches#quoteEmail"

  post "loyalty/referral" => "loyalty#create_referral"
  get  "loyalty/user_referrals" => "loyalty#user_referrals"
  get  "loyalty/find_referrals" => "loyalty#find_referrals"
  get  "loyalty/referral/:id" => "loyalty#referral"
  put "loyalty/update_referral/:id" => "loyalty#update_referral"

  get "loyalty/points" => "loyalty#points"
  get "loyalty/rewards" => "loyalty#rewards"
  get "loyalty/purchase/:id" => "loyalty#purchase"
  post "loyalty/confirm/" => "loyalty#confirm"
  get "loyalty/details/:id/:ref_type/:ref_id" => "loyalty#details"

  #post  "loyalty/referrals" => "loyalty#create_referral"
  #get   "loyalty/:userId/referrals" => "loyalty#user_referrals"  #user
  #get   "loyalty/referrals?status=:status" => "loyalty#find_referrals"
  #get   "loyalty/referrals/:id" => "loyalty#referral"
  #put   "loyalty/referrals/:id" => "loyalty#update_referral"

  #get "loyalty/:userId/points" => "loyalty#points" #user
  #get "loyalty/activeRewards" => "loyalty#rewards" #user

  get "policies/display/:id"  =>    "policies#display"
  get "policies/policies"  =>    "policies#policies"
  get "policies/download/:id"  => "policies#download"

  get "orders/user_orders"  => "orders#user_orders"

  namespace :motor do
    resources :rtos
    resources :discounts
    resources :searches
    resources :quotes
    resources :idv_charts
  end
 
 namespace :travel do
   resources :charts
 end

 namespace :health do
   resources :charts
 end

  resources :policies
  resources :rewards 
  resources :admin_users
  resources :policy_attributes
  resources :orders
  resources :static_htmls
 
  match "/delayed_job" => DelayedJobWeb, :anchor => false
 
  root :to => "welcome#index"

end

app/views/shared/_admin_left_nav.html.erb
<ul class="nav nav-list bs-docs-sidenav is_affix">
  <li><%= link_to 'IDV Chart', motor_idv_charts_path %></li>
  <li><%= link_to 'Motor Discount', motor_discounts_path %></li>
  <li><%= link_to 'RTO', motor_rtos_path %></li>
  <li><%= link_to 'Motor Quote Requests', motor_searches_path %></li>
  <li><%= link_to 'Users', admin_users_path %></li>
  <li><%= link_to 'Rewards', rewards_path %></li>
  <li><%= link_to 'Referrals', {:controller => "/loyalty", :action => "find_referrals" }  %></li>
  <li><%= link_to 'Travel Chart', travel_charts_path  %></li>
  <li><%= link_to 'Health Chart', health_charts_path  %></li>
  <li><%= link_to 'Policy Attributes', policy_attributes_path  %></li>
  <li><%= link_to 'Cutomer Orders', orders_path  %></li>
  
</ul>

app/views/shared/_ads_banner.html.erb
<div id="adsBannerDiv">
	<div class="is_right-hand-div-all-border">   
		<img src="/assets/ads/callback.jpg" usemap="#map1" />
		<map name="map1">
			<area shape="rect" coords="165,57,246,81" onclick="CallUs.show();"  href="javascript:void(0);" style="cursor: pointer;" />
		</map>
	</div>
	<div class="is_right-hand-div-all-border">
		<img src="/assets/ads/Verdananewcashback.gif" usemap="#map2" />
		<map name="map2">
			<area shape="rect" coords="122,106,261,131" onclick="bootbox.alert('fill details over here');" href="javascript:void(0);" style="cursor: pointer;" />
			<area shape="rect" coords="147,126,265,154" onclick="ReferFriend.show();" href="javascript:void(0);" style="cursor: pointer;" />
		</map>
	</div>
	<div>
		<img src="/assets/ads/VerdanaNewSignup.png" usemap="#map3" style="height:168px;"/>
		<map name="map3">
			<!--<area shape="rect" coords="115,104,261,121" onclick="alert('fill details over here');" nohref="nohref" style="cursor: pointer;" />-->
			<area shape="rect" coords="0,0,261,144" href="/login" style="cursor: pointer;" />
		</map>		 
	</div>
</div>

app/views/shared/_error_message_modal.html.erb
<!-- Modal -->
<div id="errorMessageModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Oh snap! You got an error!</h3>
  </div>
  <div class="modal-body alert alert-error" id="errorMessageModalBody">
  </div>
  <div class="modal-footer">
    <button class="btn is_btn-custom" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/shared/_form_disable_modal.html.erb
<div id="formDisableDisplay" style="display:none">
  <div class="alert">
    To start over, Please click on Reset the form link.
  </div>
</div>

app/views/shared/_help_left.html.erb
<div class="is_right-hand-div">
	<div class="alert is_alert-heading" style="border-radius: 6px 6px 0 0;">
		<strong>Help</strong>
	</div>
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
			<div class="active item">
				<p>
					<strong>Compare, Buy and Earn</strong>
				</p>
				<ul>
					<li>Compare price and features of Motor, Health and Travel Policy.</li>
					<li>Easy step to buy using Cash, Credit Card or Cheque.</li>
					<li>Earn Rewards points for every insurance purchase or refer a friend who buy insurance from us.</li>
				</ul>
			</div>
			<div class="item">
				<p>
					<strong>Our Services</strong>
				</p>
				<ul>
					<li>Guaranteed Lowest Premiums</li>
					<li>Neutral advise as we can provide Insurance from all Companies</li>
					<li>Strong Technical Domain Expertise</li>
					<li>Rewards for every purchase and reference</li>
					<li>Personalized and speedy claim services</li>
				</ul>
			</div>
			<div class="item">
				<p>
					<strong>We Offer</strong>
				</p>
				<ul>
					<li>Free chaque or Cash Pick-up in National Capital region</li>
					<li>Free Policy Delivery in National Capital region</li>
					<li>Download your Policy anytime</li>
					<li>Policy Renewal reminder</li>
					<li>Free and unbiased insurance Advisor Services</li>
				</ul>
			</div>
		</div>
		<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  		<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
</div> 

app/views/shared/_operator_left_nav.html.erb
<ul class="nav nav-list bs-docs-sidenav is_affix">
  <li><%= link_to 'Users', admin_users_path %></li>
  <li><%= link_to 'Rewards', rewards_path %></li>
  <li><%= link_to 'Referrals', {:controller => "/loyalty", :action => "find_referrals" }  %></li>
  <li><%= link_to 'Cutomer Orders', orders_path  %></li>
  
</ul>

app/views/shared/_refer_friend.html.erb
    <div id="referFriendFormDiv" class="is_right-hand-div" style="display:none;">
        <div class="alert is_alert-heading" style="border-radius: 6px 6px 0 0;">
            <button type="button" class="close" onClick="AdsBanner.show(); return false;">&times;</button>
            <strong>Refer Friend & Earn Money</strong>
        </div>
        <div id="referralFormNotificationDiv">
        </div>
        <div>
            <form method="post" action="" id="referralForm" class="callUsForm">
                <fieldset>
                   <div class="control-group">
                        <label class="control-label" for="mobile">Your Mobile Number</label>
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-mobile-phone"></i></span>
                                <input type="text" id="mobile" name="mobile" placeholder="Your Mobile" class="input-medium"></input>
                            </div>
                        </div>
                    </div> 
                   <div class="control-group">
                        <label class="control-label" for="email">Your Email address</label>
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-envelope"></i></span>
                                <input type="text" id="email" name="email" placeholder="abc@gmail.com" class="input-medium"></input>
                            </div>                              
                        </div>
                    </div> 
                   <div class="control-group">
                        <label class="control-label" for="ref_name">Referral Name</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-user"></i></span>
                            <input type="text" id="ref_name" name="ref_name" placeholder="Referral Name" class="input-medium"></input>
                        </div>
                    </div> 
                    <div class="control-group">
                        <label class="control-label" for="ref_mobile">Referral Mobile</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-mobile-phone"></i></span>
                            <input type="text" id="ref_mobile" name="ref_mobile" placeholder="Referral Mobile" class="input-medium"></input>
                        </div>
                    </div> 
                    <div class="control-group">
                        <label class="control-label" for="ref_desc">Referral Details</label>
                        <div class="controls">
                          <textarea id="ref_desc" name="ref_desc" rows="4" cols="10" ></textarea>
                        </div>
                    </div> 
                    <div class="control-group">
                        <div class="controls">
                           <button type="submit" class="btn is_btn-custom">Submit</button>
                        </div>
                    </div>  
                </fieldset>
            </form>
        </div>
    </div>

app/views/shared/_reminder.html.erb
    <div id="reminderFormDiv" class="is_right-hand-div" style="display:none;">
        <div class="alert is_alert-heading" style="border-radius: 6px 6px 0 0;">
            <button type="button" class="close" onClick="__root__showAdsBanner(); return false;">&times;</button>
            <strong>Policy Renewal Reminder</strong>
        </div>
        <div id="reminderFormNotificationDiv">
        </div>
        <div>
            <form method="post" action="" id="reminderForm" class="callUsForm">
                <fieldset>
                   <div class="control-group">
                        <label class="control-label" for="name">Your Name</label>
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-mobile-phone"></i></span>
                                <input type="text" id="name" name="name" placeholder="Your Name" class="input-medium"></input>
                            </div>
                        </div>
                    </div> 
                   <div class="control-group">
                        <label class="control-label" for="email">Your Email</label>
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-envelope"></i></span>
                                <input type="text" id="email" name="email" placeholder="abc@gmail.com" class="input-medium"></input>
                            </div>                              
                        </div>
                    </div> 
                   <div class="control-group">
                        <label class="control-label" for="mobile">Mobile</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-user"></i></span>
                            <input type="text" id="mobile" name="mobile" placeholder="Your Mobile Number" class="input-medium"></input>
                        </div>
                    </div> 
                    <div class="control-group">
                        <label class="control-label" for="ref_mobile">Policy Expiry Date</label>
                        <div class="controls input-prepend">
                            <select id="make" name="make" class="span2"></select>
                            <label>&nbsp;&nbsp;&nbsp;</label>
                            <select id="model" name="idv_chart_id" class="span2"></select>
                        </div>
                    </div> 
                    <div class="control-group">
                        <label class="control-label" for="remarks">Reminder Remarks</label>
                        <div class="controls">
                          <textarea id="remarks" name="remarks" rows="4" cols="10" ></textarea>
                        </div>
                    </div> 
                    <div class="control-group">
                        <div class="controls">
                           <button type="submit" class="btn is_btn-custom">Submit</button>
                        </div>
                    </div>  
                </fieldset>
            </form>
        </div>
    </div>

app/views/shared/_request_callback.html.erb
	<div id="requestCallBackFormDiv" class="is_right-hand-div" style="display: none;">
		<div class="alert is_alert-heading" style="border-radius: 6px 6px 0 0;">
			<button type="button" class="close" onClick="AdsBanner.show(); return false;">&times;</button>
			<strong>Request a call back!!</strong>
		</div>
		<div id="callUsFormNotificationDiv">
		</div>
		<div>
			<form method="post" action="" id="callUsForm" >
				  <fieldset>
					   <div class="control-group">
	  						<label class="control-label" for="mobile_number">Mobile Number</label>
					  		<div class="controls">
					  			<div class="input-prepend">
						  			<span class="add-on"><i class="icon-mobile-phone"></i></span>
						    		<input type="text" id="mobile_number" name="mobile_number" placeholder="mobile number" class="input-medium"></input>
					    		</div>
					    	</div>
					    </div>    
					    <div class="control-group">
	  						<label class="control-label" for="email_address">Email address</label>
					  		<div class="controls">
					  			<div class="input-prepend">
						  			<span class="add-on"><i class="icon-envelope"></i></span>				  			
					    			<input type="text" id="email_address" name="email_address" placeholder="abc@gmail.com" class="input-medium"></input>
					    		</div>				    			
					    	</div>
					    </div>  
					    <div class="control-group">
							<div class="controls">
								<button type="submit" class="btn is_btn-custom">Submit</button>
							</div>
						</div>  
				  </fieldset>
			</form>
		</div>
	</div>

app/views/shared/_user_left_nav.html.erb
<div style="margin-bottom:20px;" id="userMenuDiv">
	<ul class="nav nav-list bs-docs-sidenav">
	  <li><%= link_to '<i class="icon-edit"></i> Edit Profile'.html_safe, edit_user_registration_path, :id => "editProfile"  %></li>
	  <li><a id="myPolicies" href="#"><i class="icon-book"></i>My Policies</a></li>
	  <li><a id="myReferrals" href="#"><i class="icon-group"></i>My Referrals</a></li>
	  <li><a id="myPoints" href="#"><i class="icon-magic"></i>My Points</a></li>
	  <li><a id="myRewards" href="#"><i class="icon-gift"></i>My Rewards</a></li>
	  <li><a id="myOrders" href="#"><i class="icon-thumbs-up"></i>My Orders</a></li>
	</ul>
</div>