config/routes.rb
Nikrik::Application.routes.draw do

 
  resources :reminders


  devise_for :users,:path => '', path_names:{sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end


  get "welcome/index"
  get "home/admin"
  post "home/callus" => "home#callus"
  get "home/complaint" => "home#new_complaint"
  post "home/complaint" => "home#complaint"
  get "home/contactus" => "home#new_contactus"
  get "home/aboutus" => "home#aboutus"
  get "home/disclaimer" => "home#disclaimer"
  get "home/privatepolicy" => "home#privatepolicy"
  post "home/contactus" => "home#contactus"
  get "home/faq" => "home#faq"

  get "motor/idv_charts/distinctMakers" => "motor/idv_charts#distinctMakers"
  get "motor/idv_charts/modelsForAManufacturer" => "motor/idv_charts#modelsForAManufacturer"
  get "motor/idv_charts/:id/motorValue" => "motor/idv_charts#motorValue"
  get "motor/idv_charts/models" => "motor/idv_charts#models"
  get  "motor/searches/currentUser" => "motor/searches#currentUser"
  post "motor/searches/quote" => "motor/searches#quote"
  post "motor/searches/buy" => "motor/searches#buy"
  post "motor/searches/quoteEmail" => "motor/searches#quoteEmail"  
  
  post "health/searches/quote" => "health/searches#quote"
  post "health/searches/buy" => "health/searches#buy"
  post "health/searches/quoteEmail" => "health/searches#quoteEmail"  

  post "travel/searches/quote" => "travel/searches#quote"
  post "travel/searches/buy" => "travel/searches#buy"
  post "travel/searches/quoteEmail" => "travel/searches#quoteEmail"

  post "loyalty/referral" => "loyalty#create_referral"
  get  "loyalty/user_referrals" => "loyalty#user_referrals"
  get  "loyalty/find_referrals" => "loyalty#find_referrals"
  get  "loyalty/referral/:id" => "loyalty#referral"
  put "loyalty/update_referral/:id" => "loyalty#update_referral"

  get "loyalty/points" => "loyalty#points"
  get "loyalty/rewards" => "loyalty#rewards"
  get "loyalty/purchase/:id" => "loyalty#purchase"
  post "loyalty/confirm/" => "loyalty#confirm"
  get "loyalty/details/:id/:ref_type/:ref_id" => "loyalty#details"

  #post  "loyalty/referrals" => "loyalty#create_referral"
  #get   "loyalty/:userId/referrals" => "loyalty#user_referrals"  #user
  #get   "loyalty/referrals?status=:status" => "loyalty#find_referrals"
  #get   "loyalty/referrals/:id" => "loyalty#referral"
  #put   "loyalty/referrals/:id" => "loyalty#update_referral"

  #get "loyalty/:userId/points" => "loyalty#points" #user
  #get "loyalty/activeRewards" => "loyalty#rewards" #user

  get "policies/display/:id"  =>    "policies#display"
  get "policies/policies"  =>    "policies#policies"
  get "policies/download/:id"  => "policies#download"

  get "orders/user_orders"  => "orders#user_orders"

  namespace :motor do
    resources :rtos
    resources :discounts
    resources :searches
    resources :quotes
    resources :idv_charts
  end
 
 namespace :travel do
   resources :charts
 end

 namespace :health do
   resources :charts
 end

  resources :policies
  resources :rewards 
  resources :admin_users
  resources :policy_attributes
  resources :orders
  resources :static_htmls
 
  match "/delayed_job" => DelayedJobWeb, :anchor => false
 
  root :to => "welcome#index"

end

app/models/policy_attribute.rb
class PolicyAttribute < ActiveRecord::Base
  attr_accessible :attrib_name, :attrib_value, :company_id, :plan, :policy_type, :order_num
  belongs_to :company,  :class_name => 'Company'

  def self.find_By_policy_type( policy_type)
    where("policy_type = ? ", policy_type ).order("order_num asc, company_id asc")
  end

end

app/controllers/policy_attributes_controller.rb
class PolicyAttributesController < ApplicationController
  # GET /policy_attributes
  # GET /policy_attributes.json
  def index
     policy_type = params[:type]
     if ( policy_type.blank?)
       @policy_attributes = PolicyAttribute.order("policy_type, order_num asc, company_id asc").all
     else
        @policy_attributes = PolicyAttribute.find_By_policy_type(policy_type)
     end
    child_hash = Hash.new
    parent_hash = Hash.new
    prev_attribute_name = ""
    @policy_attributes.each do |attribute|

      if (prev_attribute_name != attribute.attrib_name)
        parent_hash[prev_attribute_name] = child_hash unless prev_attribute_name == ""
        child_hash = Hash.new
        prev_attribute_name = attribute.attrib_name
      end
      if attribute.plan.blank?
        child_hash[attribute.company_id] = attribute.attrib_value
      else
        child_hash["#{attribute.company_id}:#{attribute.plan}"] = attribute.attrib_value
      end
    
    end

    #for last attribute
    parent_hash[prev_attribute_name] = child_hash unless prev_attribute_name == ""

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: parent_hash }
    end
  end

  # GET /policy_attributes/1
  # GET /policy_attributes/1.json
  def show
    @policy_attribute = PolicyAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @policy_attribute }
    end
  end

  # GET /policy_attributes/new
  # GET /policy_attributes/new.json
  def new
    @policy_attribute = PolicyAttribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @policy_attribute }
    end
  end

  # GET /policy_attributes/1/edit
  def edit
    @policy_attribute = PolicyAttribute.find(params[:id])
  end

  # POST /policy_attributes
  # POST /policy_attributes.json
  def create
    @policy_attribute = PolicyAttribute.new(params[:policy_attribute])

    respond_to do |format|
      if @policy_attribute.save
        format.html { redirect_to @policy_attribute, notice: 'Policy attribute was successfully created.' }
        format.json { render json: @policy_attribute, status: :created, location: @policy_attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @policy_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /policy_attributes/1
  # PUT /policy_attributes/1.json
  def update
    @policy_attribute = PolicyAttribute.find(params[:id])

    respond_to do |format|
      if @policy_attribute.update_attributes(params[:policy_attribute])
        format.html { redirect_to @policy_attribute, notice: 'Policy attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @policy_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policy_attributes/1
  # DELETE /policy_attributes/1.json
  def destroy
    @policy_attribute = PolicyAttribute.find(params[:id])
    @policy_attribute.destroy

    respond_to do |format|
      format.html { redirect_to policy_attributes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/policy_attributes_helper.rb
module PolicyAttributesHelper
end

app/views/policy_attributes/_form.html.erb
<%= simple_form_for(@policy_attribute) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :company, :label_method => :name, :value_method => :id,  :prompt => "Select Company", :required => true %>
    <%= f.input :policy_type ,:required => true, :prompt => "Select Type", :collection => [ "Motor", "Health", "Travel"] %>
    <%= f.input :plan %>
    <%= f.input :attrib_name , :required => true %>
    <%= f.input :attrib_value , :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/policy_attributes/edit.html.erb
<h2>Editing Policy Attribute</h2>

<%= render 'form' %>

<%= link_to 'Show', @policy_attribute %> |
<%= link_to 'Back', policy_attributes_path %>

app/views/policy_attributes/index.html.erb
<h2>Listing Policy Attributes</h2>
<div>
<form method="get" action="/policy_attributes" class="form-horizontal" >
  <select type="text" name="type" >
   <option value="MOTOR" >MOTOR</option>
   <option value="HEALTH" >HEALTH</option>
   <option value="TRAVEL" >TRAVEL</option>
 </select>
 <input type="submit" name="search" value="Search" />
</form>
</div>


<p><%= link_to 'Add Policy attribute', new_policy_attribute_path, :class => "btn" %></p>
<table class="table table-bordered table-striped">
  <tr>
    <th>Policy type</th>
    <th>Order Number</th>
    <th>Company</th>
    <th>Plan</th>
    <th>Attribute name</th>
    <th>Attribute value</th>
    <th></th>
    <th></th>
  </tr>

<% @policy_attributes.each do |policy_attribute| %>
  <tr>
    <td><%= policy_attribute.policy_type %></td>
    <td><%= policy_attribute.order_num %></td>
    <td><%= policy_attribute.company.name %></td>
    <td><%= policy_attribute.plan %></td>
    <td><%= policy_attribute.attrib_name %></td>
    <td><%= policy_attribute.attrib_value %></td>
    <td><%= link_to 'Show', policy_attribute %></td>
    <td><%= link_to 'Edit', edit_policy_attribute_path(policy_attribute) %></td>
  </tr>
<% end %>
</table>
<p><%= link_to 'Add Policy attribute', new_policy_attribute_path, :class => "btn" %></p>
<br />

app/views/policy_attributes/new.html.erb
<h2>New Policy Aattribute</h2>

<%= render 'form' %>

<%= link_to 'Back', policy_attributes_path %>

app/views/policy_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @policy_attribute.company_id %>
</p>

<p>
  <b>Policy type:</b>
  <%= @policy_attribute.policy_type %>
</p>

<p>
  <b>Plan:</b>
  <%= @policy_attribute.plan %>
</p>

<p>
  <b>Attrib name:</b>
  <%= @policy_attribute.attrib_name %>
</p>

<p>
  <b>Attrib value:</b>
  <%= @policy_attribute.attrib_value %>
</p>


<%= link_to 'Edit', edit_policy_attribute_path(@policy_attribute) %> |
<%= link_to 'Back', policy_attributes_path %>