config/routes.rb
Nikrik::Application.routes.draw do

 
  resources :reminders


  devise_for :users,:path => '', path_names:{sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end


  get "welcome/index"
  get "home/admin"
  post "home/callus" => "home#callus"
  get "home/complaint" => "home#new_complaint"
  post "home/complaint" => "home#complaint"
  get "home/contactus" => "home#new_contactus"
  get "home/aboutus" => "home#aboutus"
  get "home/disclaimer" => "home#disclaimer"
  get "home/privatepolicy" => "home#privatepolicy"
  post "home/contactus" => "home#contactus"
  get "home/faq" => "home#faq"

  get "motor/idv_charts/distinctMakers" => "motor/idv_charts#distinctMakers"
  get "motor/idv_charts/modelsForAManufacturer" => "motor/idv_charts#modelsForAManufacturer"
  get "motor/idv_charts/:id/motorValue" => "motor/idv_charts#motorValue"
  get "motor/idv_charts/models" => "motor/idv_charts#models"
  get  "motor/searches/currentUser" => "motor/searches#currentUser"
  post "motor/searches/quote" => "motor/searches#quote"
  post "motor/searches/buy" => "motor/searches#buy"
  post "motor/searches/quoteEmail" => "motor/searches#quoteEmail"  
  
  post "health/searches/quote" => "health/searches#quote"
  post "health/searches/buy" => "health/searches#buy"
  post "health/searches/quoteEmail" => "health/searches#quoteEmail"  

  post "travel/searches/quote" => "travel/searches#quote"
  post "travel/searches/buy" => "travel/searches#buy"
  post "travel/searches/quoteEmail" => "travel/searches#quoteEmail"

  post "loyalty/referral" => "loyalty#create_referral"
  get  "loyalty/user_referrals" => "loyalty#user_referrals"
  get  "loyalty/find_referrals" => "loyalty#find_referrals"
  get  "loyalty/referral/:id" => "loyalty#referral"
  put "loyalty/update_referral/:id" => "loyalty#update_referral"

  get "loyalty/points" => "loyalty#points"
  get "loyalty/rewards" => "loyalty#rewards"
  get "loyalty/purchase/:id" => "loyalty#purchase"
  post "loyalty/confirm/" => "loyalty#confirm"
  get "loyalty/details/:id/:ref_type/:ref_id" => "loyalty#details"

  #post  "loyalty/referrals" => "loyalty#create_referral"
  #get   "loyalty/:userId/referrals" => "loyalty#user_referrals"  #user
  #get   "loyalty/referrals?status=:status" => "loyalty#find_referrals"
  #get   "loyalty/referrals/:id" => "loyalty#referral"
  #put   "loyalty/referrals/:id" => "loyalty#update_referral"

  #get "loyalty/:userId/points" => "loyalty#points" #user
  #get "loyalty/activeRewards" => "loyalty#rewards" #user

  get "policies/display/:id"  =>    "policies#display"
  get "policies/policies"  =>    "policies#policies"
  get "policies/download/:id"  => "policies#download"

  get "orders/user_orders"  => "orders#user_orders"

  namespace :motor do
    resources :rtos
    resources :discounts
    resources :searches
    resources :quotes
    resources :idv_charts
  end
 
 namespace :travel do
   resources :charts
 end

 namespace :health do
   resources :charts
 end

  resources :policies
  resources :rewards 
  resources :admin_users
  resources :policy_attributes
  resources :orders
  resources :static_htmls
 
  match "/delayed_job" => DelayedJobWeb, :anchor => false
 
  root :to => "welcome#index"

end

app/models/health/chart.rb
class Health::Chart < ActiveRecord::Base
	self.table_name = "health_charts"
  attr_accessible :company_id,:plan, :age_end, :age_start,:adults, :childs, :coverage, :premium

  def to_s
    "HealthChart: #{@comapny_id}--#{@age_end} (#{@coverage} adults=#{@adults} childs=#{@childs}"
  end

  def self.find_by_coverage_age(heath_cover, age, adults, childs)
    where("coverage = ? AND age_start <= ? and age_end >= ? and adults=? and childs=? ", heath_cover, age, age , adults, childs)
  end

  def self.find_by_company(company_id)
    where("company_id = ?", company_id)
  end

end

app/models/travel/chart.rb
class Travel::Chart < ActiveRecord::Base
	self.table_name = "travel_charts"
  attr_accessible :company_id, :policy_for,:trip_type,:max_trip_duration, :age_end, :age_start, :coverage, :duration_start,:duration_end, :has_usa, :plan, :adult, :child, :premium


  def self.find_premium_for_single_trip( input, days, has_usa)
    where("coverage = ? AND age_start <= ? and age_end >= ? and duration_start <= ? and duration_end >= ? and has_usa = ? and policy_for = ? and trip_type = 'S' ", input.travel_cover, input.age, input.age, days,days, has_usa, input.policy_for).order("company_id")
  end

  def self.find_premium_for_multiple_trip( input)
    where("coverage = ? AND age_start <= ? and age_end >= ? and max_trip_duration = ? and policy_for = 'I' and trip_type = 'M' ", input.travel_cover, input.age, input.age, input.max_trip_duration ).order("company_id")
  end
  
  def self.find_by_company(company_id)
    where("company_id = ?", company_id)
  end

  def self.find_premium_for_single_trip_company( input, age, days, has_usa,company_id)
    where("coverage = ? AND age_start <= ? and age_end >= ? and duration_start <= ? and duration_end >= ? and has_usa = ? and policy_for = ? and trip_type = 'S' and company_id = ? ", input.travel_cover, age, age, days,days, has_usa, input.policy_for,company_id)
  end

  def self.find_premium_for_single_trip_company_members( input, age, days, has_usa,company_id, adult, child)
    where("coverage = ? AND age_start <= ? and age_end >= ? and duration_start <= ? and duration_end >= ? and has_usa = ? and policy_for = ? and trip_type = 'S' and company_id = ? and adult = ? and child= ? ", input.travel_cover, age, age, days,days, has_usa, input.policy_for,company_id,adult,child)
  end

  def self.find_premium_for_single_trip_TATA( input, age, days, has_usa)
    where("coverage = ? AND age_start <= ? and age_end >= ? and duration_start <= ? and duration_end >= ? and has_usa = ? and trip_type = 'S' and company_id = 3 and plan in ( 'Silver', 'Silver Plus' ) ", input.travel_cover, age, age, days,days, has_usa)
  end

end

app/models/travel/member.rb
class Travel::Member < ActiveRecord::Base
  self.table_name = "travel_members"
  attr_accessible :id, :relationship, :age, :search_id
  belongs_to :travel_search , :class_name => "Travel::Search"
end

app/models/travel/quote.rb
include ActionView::Helpers::NumberHelper

class Travel::Quote
  attr_accessor :company_id, :company_name, :total_premium, :service_tax, :final_premium,:plan, :points,:user_id, :travel_search_id
  	

  def self.format_fields (quote)
    quote.total_premium = ((quote.total_premium.nil?)? 0 : quote.total_premium.ceil )
    quote.final_premium = ((quote.final_premium.nil?)? 0 : quote.final_premium.ceil )
    quote.points = ((quote.points.nil?)? 0 : quote.points.ceil )
  end

 end

app/models/travel/search.rb
class Travel::Search < ActiveRecord::Base
  self.table_name = "travel_searches"
  attr_accessible :id, :policy_for, :trip_type,:max_trip_duration, :age, :location,:travel_cover, :start_date,:end_date, :name, :email_id, :mobile_number, :address, :company_name,:plan, :final_premium , :members_attributes
  
  has_many :members ,:class_name => "Travel::Member" , :dependent => :destroy
  accepts_nested_attributes_for :members

end

app/controllers/health/charts_controller.rb
class Health::ChartsController < ApplicationController
  # GET /health_charts
  # GET /health_charts.json
  def index
     company_id = params[:company_id]
    if company_id.nil?
      company_id = '1'
    end

    @health_charts = Health::Chart.find_by_company(company_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @health_charts }
    end
  end

  # GET /health_charts/1
  # GET /health_charts/1.json
  def show
    @health_chart = Health::Chart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @health_chart }
    end
  end

  # GET /health_charts/new
  # GET /health_charts/new.json
  def new
    @health_chart = Health::Chart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @health_chart }
    end
  end

  # GET /health_charts/1/edit
  def edit
    @health_chart = Health::Chart.find(params[:id])
  end

  # POST /health_charts
  # POST /health_charts.json
  def create
    @health_chart = Health::Chart.new(params[:health_chart])

    respond_to do |format|
      if @health_chart.save
        format.html { redirect_to @health_chart, notice: 'Health chart was successfully created.' }
        format.json { render json: @health_chart, status: :created, location: @health_chart }
      else
        format.html { render action: "new" }
        format.json { render json: @health_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /health_charts/1
  # PUT /health_charts/1.json
  def update
    @health_chart = Health::Chart.find(params[:id])

    respond_to do |format|
      if @health_chart.update_attributes(params[:health_chart])
        format.html { redirect_to @health_chart, notice: 'Travel chart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @health_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_charts/1
  # DELETE /health_charts/1.json
  def destroy
    @health_chart = Health::Chart.find(params[:id])
    @health_chart.destroy

    respond_to do |format|
      format.html { redirect_to health_charts_url }
      format.json { head :no_content }
    end
  end

  def company_data
  
  end

end

app/controllers/travel/charts_controller.rb
class Travel::ChartsController < ApplicationController
  # GET /travel_charts
  # GET /travel_charts.json
  def index
    company_id = params[:company_id]
    if company_id.nil?
      company_id = '1'
    end

    @travel_charts = Travel::Chart.find_by_company(company_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travel_charts }
    end
  end

  # GET /travel_charts/1
  # GET /travel_charts/1.json
  def show
    @travel_chart = Travel::Chart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travel_chart }
    end
  end

  # GET /travel_charts/new
  # GET /travel_charts/new.json
  def new
    @travel_chart = Travel::Chart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travel_chart }
    end
  end

  # GET /travel_charts/1/edit
  def edit
    @travel_chart = Travel::Chart.find(params[:id])
  end

  # POST /travel_charts
  # POST /travel_charts.json
  def create
    @travel_chart = Travel::Chart.new(params[:travel_chart])

    respond_to do |format|
      if @travel_chart.save
        format.html { redirect_to @travel_chart, notice: 'Travel chart was successfully created.' }
        format.json { render json: @travel_chart, status: :created, location: @travel_chart }
      else
        format.html { render action: "new" }
        format.json { render json: @travel_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /travel_charts/1
  # PUT /travel_charts/1.json
  def update
    @travel_chart = Travel::Chart.find(params[:id])

    respond_to do |format|
      if @travel_chart.update_attributes(params[:travel_chart])
        format.html { redirect_to @travel_chart, notice: 'Travel chart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travel_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travel_charts/1
  # DELETE /travel_charts/1.json
  def destroy
    @travel_chart = Travel::Chart.find(params[:id])
    @travel_chart.destroy

    respond_to do |format|
      format.html { redirect_to travel_charts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/travel/searches_controller.rb
class Travel::SearchesController < ApplicationController
  wrap_parameters :search, :format => [:json, :xml]

  def index
    @searches = Travel::Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  def show
    @search = Travel::Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end


def quote
   #valid_json_format = '{"cng_type":"LPG","cng_value":1000,"elec_acc":200,"has_anti_theft":true,"has_claim":true,"idv_chart_id":1,"is_aai_member":false,"ncb":20,"new_policy":false,"non_elec_acc":2000,"passenger_coverage_amt":100000,"policy_exp_date":"2012-12-12","register_city":"Delhi","register_type":"Company","year_of_manufacture":"2012-12-12"}'
   Rails.logger.error "New post: #{params[:search].inspect}"
   new_search = Travel::Search.new(params[:search] )

   new_search.save

   premiums = Travel::Premium.new(new_search).calculate_premium

   premiums.each do |premium|    
    premium.travel_search_id = new_search.id
    Rails.logger.info "Final Premium= #{user_signed_in?}"
    Rails.logger.info "Final Premium= #{current_user}"
    if (user_signed_in? && (current_user.has_role? :user) )
          premium.user_id = current_user.id
    end
   end

   respond_to do |format|
    format.json { render json: premiums }
   end
   
  end

  def buy
    
    existing_travel_search = Travel::Search.find(params[:id])
    existing_travel_search.company_name = params[:company_name]
    existing_travel_search.final_premium = params[:final_premium]
    existing_travel_search.name = params[:name]
    existing_travel_search.email_id = params[:email_id]
    existing_travel_search.mobile_number = params[:mobile_number]
    existing_travel_search.address = params[:address]     

    existing_travel_search.save

    ContactMailer.delay.buy_travel_email(existing_travel_search)

    render :json => existing_travel_search

  end

  def quoteEmail
    Rails.logger.info "Email quote object= #{params}"
    ContactMailer.delay.quote_travel_email(params[:name], params[:email_id], params[:mail])
    render :json => params
  end   

end

app/views/travel/charts/_form.html.erb
<%= simple_form_for(@travel_chart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_id %>
    <%= f.input :policy_for %>
    <%= f.input :trip_type %>
    <%= f.input :max_trip_duration %>
    <%= f.input :coverage %>
    <%= f.input :age_start %>
    <%= f.input :age_end %>
    <%= f.input :plan %>
    <%= f.input :duration_start %>
    <%= f.input :duration_end %>
    <%= f.input :has_usa %>
    <%= f.input :premium %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/travel/charts/edit.html.erb
<h1>Editing Travel Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel_chart %> |
<%= link_to 'Back', travel_charts_path %>

app/views/travel/charts/index.html.erb
<h2>Listing Travel Charts</h2>


<div>
<form method="get" action="/travel/charts" class="form-horizontal" >
  <select type="text" name="company_id" >
   <option value="1" >ICICI</option>
   <option value="2" >BAJAJ</option>
   <option value="3" >TATA</option>
   <option value="4" >RELIANCE</option>
   <option value="5" >Apollo Munich</option>
   <option value="6" >Max Bupa</option>
   <option value="7" >Religare</option>
   <option value="8" >HDFC</option>
   <option value="9" >Bharti Axa</option>
   <option value="10" >IFFCO Tokio</option>
   <option value="11" >L&T</option>
   <option value="12" >National</option>
   <option value="13" >United India</option>
  </select>
 <input type="submit" name="search" value="Search" />
</form>
</div>

<p><%= link_to 'Add Travel Record', new_travel_chart_path, :class => "btn" %></p>

<table class="table table-bordered table-striped" >
  <tr>
    <th>Company</th>
    <th>Policy For</th>
    <th>Trip Type</th>
    <th>Max Trip Duration</th>
    <th>Coverage</th>
    <th>Age start</th>
    <th>Age end</th>
    <th>Plan</th>
    <th>Duration Start</th>
    <th>Duration End</th>
    <th>Has usa</th>
    <th>Premium</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @travel_charts.each do |travel_chart| %>
  <tr>
    <td><%= travel_chart.company_id %></td>
    <td><%= travel_chart.policy_for %></td>
    <td><%= travel_chart.trip_type %></td>
    <td><%= travel_chart.max_trip_duration %></td>
    <td><%= travel_chart.coverage %></td>
    <td><%= travel_chart.age_start %></td>
    <td><%= travel_chart.age_end %></td>
    <td><%= travel_chart.plan %></td>
    <td><%= travel_chart.duration_start %></td>
    <td><%= travel_chart.duration_end %></td>
    <td><%= travel_chart.has_usa %></td>
    <td><%= travel_chart.premium %></td>
    <td><%= link_to 'Show', travel_chart %></td>
    <td><%= link_to 'Edit', edit_travel_chart_path(travel_chart) %></td>
    <td><%= link_to 'Destroy', travel_chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Travel Record', new_travel_chart_path, :class => "btn"  %>

app/views/travel/charts/new.html.erb
<h1>New Travel Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', travel_charts_path %>

app/views/travel/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @travel_chart.company_id %>
</p>

<p>
  <b>Coverage:</b>
  <%= @travel_chart.coverage %>
</p>

<p>
  <b>Age start:</b>
  <%= @travel_chart.age_start %>
</p>

<p>
  <b>Age end:</b>
  <%= @travel_chart.age_end %>
</p>

<p>
  <b>Plan:</b>
  <%= @travel_chart.plan %>
</p>

<p>
  <b>Days:</b>
  <%= @travel_chart.days %>
</p>

<p>
  <b>Has usa:</b>
  <%= @travel_chart.has_usa %>
</p>

<p>
  <b>Premium:</b>
  <%= @travel_chart.premium %>
</p>


<%= link_to 'Edit', edit_travel_chart_path(@travel_chart) %> |
<%= link_to 'Back', travel_charts_path %>